# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1458229780338866c54ce29e4b96c7589e6513cdde1559691228515cb72a85f134600290dc6213eaef8ccc8aeb4891b5079d7d41c942398e6e124d28de549cf

test:
  secret_key_base: 88002fd6046a1e4dad63b30d9f851662cfc6789b9a1fa222d346f864e5215f91dbc4f778aaf9e13a8d0137ade8e258f5e6b92246976972edf7b1f2e3bde4e987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
